version: '3'
services:
  retaildb:
    image: postgres
    container_name: retail
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retaildb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # retailpgadmintweb:
  #   image: dpage/pgadmin4
  #   container_name: retailpgadmintweb
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - '5052:80'
  #   depends_on:
  #     - retaildb
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - '5002:5000'
    # volumes:
      # - ./:/app
    depends_on:
      - retaildb
volumes:
  postgres_data:
